### ISSUE TITLE
会报文件获取不到

### ISSUE THREAD

**Issue by lintianzhi** [zhangpeihao/docker-registry-driver-qiniu#1]
```
2015-01-25 12:24:29,802 ERROR: Exception on /v1/images/5164e74cf5bf1fa0d694b28848d0dd49d5553a213f1d25907abc5275b5dc9d50/json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 250, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 58, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 140, in wrapper
    resp = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 329, in get_image_json
    return _get_image_json(image_id, headers)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 122, in _get_image_json
    data = store.get_content(store.image_json_path(image_id))
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/qiniustorage.py", line 50, in get_content
    for buf in self.get_store(path, self.buffer_size):
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/qiniustorage.py", line 74, in get_store
    raise IOError("Could not get content: %s" % path)
IOError: Could not get content: images/5164e74cf5bf1fa0d694b28848d0dd49d5553a213f1d25907abc5275b5dc9d50/json
```

**Comment by zhangpeihao** [comment]
你有没有正确设置参数
qiniu_accesskey和qiniu_secretkey
